version: "3.8"
# edit
services:
  database:
    image: mariadb:latest
    container_name: mariadb_container
    restart: always
    environment:
      MYSQL_HOST: localhost
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_DATABASE: dylanki
      MYSQL_USER: root
      MYSQL_PASSWORD: ''
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  backend:
    build:
      context: ./src
      dockerfile: ../Dockerfile.db
    container_name: nextjs_backend
    restart: always
    environment:
      DATABASE_HOST: loaclhost
      DATABASE_USER: root
      DATABASE_PASSWORD: ''
      DATABASE_NAME: dylanki
    depends_on:
      - database
    ports:
      - "3001:3001"
    volumes:
      - ./src:/app
      - ./src/app/node_modules

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    container_name: react_frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  mariadb_data:
