services:
  database:
    extends:
      file: database.yml
      service: database
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "3902:3902"
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "python", "healthcheck.py" ]
      start_period: 30s
      interval: 30s
      timeout: 10s
      retries: 30
    environment:
      COMPOSE: "True"
  frontend:
    build:
      frontend
    ports:
      - "3000:3000"
    depends_on:
      backend:
        condition: service_healthy
